### ISSUE TITLE
Missing const?

### ISSUE THREAD

**Issue by tomas-davidovic** [carlos-urena/psc-sampler#1]
Hi, I was curious if there was a reason some of the calls like get_area() and is_invisible() are non-const? I made them const and didn't see any problem with it, but maybe I missed something.

(Also, thanks for the code, makes life much easier :-) )

**Comment by carlos-urena** [comment]
Hi, Tomas, I don't remember a reason not to made those methods const, probably I just forgot that, because I usually prefer to use 'const' whenever possible. I'll try to correct this in the repository asap, thanks for reporting it. 

(and wellcome!, I'm glad you're using our algorithm)

**Comment by carlos-urena** [comment]
I've added 'const' and everything is working fine, so you were right, thanks again!
